# Generated by Django 3.2.9 on 2021-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0003_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Accounting', 'Accounting'), ('Management', 'Management'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('finance', 'finance')], max_length=250, null=True),
        ),
    ]
